kind: pipeline
type: docker
name: sync-tifinity-io

steps:
- name: hugo build
  image: jojomi/hugo
  commands:
  - echo hello drone
  - git submodule update --init --recursive
  - ls && pwd
  - hugo --baseUrl="http://tifinity.github.io/"
  when:
    branch:
    - master

trigger:
  event:
  - push