kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
- name: ssh
  image: alpine
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - apk add openssh
    - apk add git
    - mkdir $HOME/.ssh
    - echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - cat $HOME/.ssh/id_rsa
    - git clone --recursive git@github.com:Tifinity/Tifinity-Blog.git

- name: clone
  image: centos
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - yum install -y git
    - yum install -y openssh-clients
    - mkdir $HOME/.ssh
    - echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - cat $HOME/.ssh/id_rsa
    - git clone --recursive git@github.com:Tifinity/Tifinity-Blog.git
  when:
    branch:
    - master

# - name: clone
#   image: plugins/git-action:1
#   settings:
#     actions:
#       - clone
#     remote: git@github.com:Tifinity/Tifinity-Blog.git
#     branch: master
#     path: /drone/src
#     ssh_key:
#       form_secret: GIT_PUSH_SSH_KEY

- name: hugo build
  image: klakegg/hugo
  commands:
  - pwd
  - cd Tifinity-Blog
  - hugo version
  - hugo --baseUrl="http://tifinity.github.io/"
  when:
    branch:
    - master

- name: publish
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - apk add openssh
    - mkdir $HOME/.ssh
    - echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - touch $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
    - cat $HOME/.ssh/id_rsa
    - cd Tifinity-Blog/public
    - git add .
    - git commit -m "update blog"
    - git remote set-url origin git@github.com:Tifinity/Tifinity.github.io.git
    - git push origin HEAD:master
  when:
    branch:
    - master

# - name: publish  
#   image: plugins/gh-pages
#   settings:
#     ssh_key: 
#       from_secret: SSH_KEY
#     pages_directory: Tifinity-Blog/public/
#     upstream_name: upstream

# push 静态页面到 github
# - name: push github.io
#   image: muxueqz/drone-git-push-by-bash
#   settings: 
#     branch: master
#     remote: git@github.com:Tifinity/Tifinity.github.io.git
#     force: true
#     commit: true
#     path: ./Tifinity-Blog/public
#     ssh_key:
#       from_secret: SSH_KEY

trigger:
  event:
  - push