kind: pipeline
type: docker
name: sync-tifinity-io


steps:
- name: hugo build
  image: jojomi/hugo
  commands:
  - echo hello drone
  - git version
  - git config --global http.version HTTP/1.1
  - git submodule update --init --recursive
  - ls && pwd
  - hugo --baseUrl="http://tifinity.github.io/"
  - cd public
  - git add .
  - git commit -m "update blog"
  - git remote set-url origin git@github.com:Tifinity/Tifinity.github.io.git
  - git push origin HEAD:master
  when:
    branch:
    - master

trigger:
  event:
  - push