kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - echo start clone
  - git version
  - git config --global http.version HTTP/1.1
  - git clone git://github.com/Tifinity/Tifinity-Blog.git
  - cd Tifinity-Blog
  - git submodule update --init --recursive
  when:
    branch:
    - master

- name: hugo build
  image: klakegg/hugo
  commands:
  - pwd
  - cd Tifinity-Blog
  - hugo version
  - hugo --baseUrl="http://tifinity.github.io/"
  when:
    branch:
    - master

- name: push github.io
  image: alpine/git
  commands:
  - pwd
  - cd Tifinity-Blog/public
  - git config --global http.version HTTP/1.1
  - git add .
  - git commit -m "update blog"
  - git remote set-url origin git@github.com:Tifinity/Tifinity.github.io.git
  - git push origin HEAD:master
  when:
    branch:
    - master

trigger:
  event:
  - push