kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  environment:
    SSH_KEY: 
      from_secret: git_ssh
  commands:
  # write the ssh key.
  - mkdir /root/.ssh
  - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  # add github.com to our known hosts.
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
  # start clone
  - echo start clone
  - echo $DRONE_GIT_SSH_URL
  - git version
  - git config --global http.version HTTP/1.1
  - git clone --recursive git@github.com:Tifinity/Tifinity-Blog.git
  when:
    branch:
    - master

- name: hugo build
  image: klakegg/hugo
  commands:
  - pwd
  - cd Tifinity-Blog
  - hugo version
  - hugo --baseUrl="http://tifinity.github.io/"
  when:
    branch:
    - master

# push 静态页面到 github
- name: push github.io
  image: muxueqz/drone-git-push-by-bash
  settings: 
    branch: master
    remote: git@github.com:Tifinity/Tifinity.github.io.git
    force: true
    commit: true
    path: ./Tifinity-Blog/public
    ssh_key:
      from_secret: git_ssh

trigger:
  event:
  - push