kind: pipeline
type: docker
name: sync-tifinity-io

clone:
  disable: true

steps:
- name: ssh
  image: alpine
  commands:
  - mkdir /root/.ssh
  - echo -e "$SSH_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /root/.ssh/known_hosts 2> /dev/null
- name: clone1
  image: alpine/git
  commands:
  - git clone git@github.com:Tifinity/Tifinity-Blog.git

- name: clone
  image: plugins/git-action:1
  settings:
    actions:
      - clone
    remote: git@github.com:Tifinity/Tifinity-Blog.git
    branch: master
    path: /drone/src
    ssh_key:
      form_secret: ssh

- name: hugo build
  image: klakegg/hugo
  commands:
  - pwd
  - cd Tifinity-Blog
  - hugo version
  - hugo --baseUrl="http://tifinity.github.io/"
  when:
    branch:
    - master

# push 静态页面到 github
- name: push github.io
  image: muxueqz/drone-git-push-by-bash
  settings: 
    branch: master
    remote: git@github.com:Tifinity/Tifinity.github.io.git
    force: true
    commit: true
    path: ./Tifinity-Blog/public
    ssh_key:
      from_secret: git_ssh

trigger:
  event:
  - push